[package]
name = "TaskTaskRevolution"
authors = ["Flávio Granato <flavio.granato@protonmail.com>"]
version = "0.2.0"
edition = "2021"
description = "Um utilitário de linha de comando para organizar suas tarefas e projetos."

[[bin]]
name = "ttr"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_yaml = "0.9.32"
chrono = { version = "0.4.39", features = ["serde"] }
uuid = { version = "1.6", features = ["v4", "serde"] }

[dev-dependencies]
tempfile = "3.8"
serde_test = "1.0.177"
speculate = "0.1.2"
