[package]
name = "TaskTaskRevolution"
authors = ["Flávio Granato <flavio.granato@protonmail.com>"]
version = "0.1.0"
edition = "2021"
description = "Um utilitário de linha de comando para organizar suas tarefas e projetos."


[[bin]]
name = "ttr"
path = "src/main.rs"

[dependencies]
regex = "1.11.1"
clap = { version = "4.5.29", features = ["derive"] }
serde_yaml = "0.9.32"
serde = { version = "1.0.217", features = ["derive"] }
anyhow = "1.0.95"
chrono = { version = "0.4.39", features = ["serde"] }
serde_with = { version = "3.12.0", features = ["chrono"] }
serde_test = "1.0.177"
speculate = "0.1.2"
