[package]
name = "TaskTaskRevolution"
authors = ["Flávio Granato <flavio.granato@protonmail.com>"]
version = "0.4.0"
edition = "2024"
description = "Um utilitário de linha de comando para organizar suas tarefas e projetos."


[[bin]]
name = "ttr"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34-deprecated"
chrono = { version = "0.4.40", features = ["serde"] }
uuid7 = "1.1.0"
csv = "1.3.1"

[dev-dependencies]
tempfile = "3.19.1"
speculate = "0.1.2"
criterion = "0.5.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 0
debug = 2
