apiVersion: tasktaskrevolution.io/v1alpha1
kind: Config
metadata:
  createdAt: 2024-01-01T00:00:00Z
  updatedAt: 2024-01-01T00:00:00Z
  createdBy: system
spec:
  managerName: "Project Manager"
  managerEmail: "manager@example.com"
  defaultTimezone: "UTC"
  workHoursStart: "09:00"
  workHoursEnd: "18:00"
  workDaysPerWeek: ["monday", "tuesday", "wednesday", "thursday", "friday"]
