apiVersion: tasktaskrevolution.io/v1alpha1
kind: Config
metadata:
  name: "Project Manager"
  email: "manager@example.com"
spec:
  timezone: "UTC"
  workHours:
    start: "09:00"
    end: "18:00"
  workDays: ["monday", "tuesday", "wednesday", "thursday", "friday"]
