apiVersion: tasktaskrevolution.io/v1alpha1
kind: Resource
metadata:
  id: 0199598d-0911-75f8-aefa-a85da2816b0a
  name: Test Resource
  email: test@example.com
  code: developer-2
  resourceType: Developer
  status: Available
spec:
  timeOffBalance: 0
  timeOffHistory: []
