apiVersion: tasktaskrevolution.io/v1alpha1
kind: Project
metadata:
  name: Projeto Teste
  description: Projeto para testar férias com layoff
spec:
  name: Projeto Teste
  description: Projeto para testar férias com layoff
  status: InProgress
  vacationRules:
    maxConcurrentVacations: 2
    allowLayoffVacations: true
    requireLayoffVacationPeriod: false
    layoffPeriods:
      - startDate: "2024-06-01"
        endDate: "2024-06-30"
      - startDate: "2024-12-15"
        endDate: "2024-12-31"
