apiVersion: tasktaskrevolution.io/v1alpha1
kind: Resource
metadata:
  id: 0199598b-fc12-7086-a053-dec33930a2eb
  name: John Doe
  email: john@example.com
  code: developer-1
  resourceType: Developer
  status: Available
spec:
  vacations: null
  projectAssignments: null
  timeOffBalance: 0
  timeOffHistory: []
