name: Gerar Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_e_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Executar testes
        run: cargo test --verbose

      - name: Build do projeto
        run: cargo build --release

      - name: Criar release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/ttr
          generate_release_notes: true
